version: "3.7"

services:
  caddy:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "3535:80"
      - "3536:443"
      - "3536:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:80'
      interval: 2s
      timeout: 10s
      retries: 15
volumes:
  caddy_data:
  caddy_config:
