version: "3.7"

services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80"
      - "443"
      - "443/udp"
    volumes:
      - type: bind
        source: $PWD/Caddyfile
        target: /etc/caddy/Caddyfile
      - type: bind
        source: $PWD/src/lydia.moe
        target: /srv/lydia.moe
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
