version: "3.7"

services:
  caddy:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80"
      - "443"
      - "443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test:
        - CMD
        - "wget" 
        - "--server-response" 
        - "--spider"
        - "http://localhost"
      interval: 5s
      timeout: 10s
      retries: 3
volumes:
  caddy_data:
  caddy_config:
