version: "3.7"

services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80"
      - "443"
      - "443/udp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./src/lydia.moe:/srv/lydia.moe"
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
